name: boby_movie_app
description: "A modern and user-friendly movie discovery application. Explore popular movies, access detailed information, and track your favorite films."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Core UI Components
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_staggered_animations: ^1.1.1

  # Network and Data Processing
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  flutter_cache_manager: ^3.4.1

  # State Management
  equatable: ^2.0.7
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  # Routing and Navigation
  go_router: ^15.1.1

  # Local Storage and Device Info
  device_info_plus: ^11.4.0
  get_it: ^8.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true


  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
